---
title: "Infectious disease modelling_SIS model"
author: "Finta Francis"
format: html
editor: visual
---
SIS MODEL STRUCTURE

We have:

S → I (infection)
I → S (recovery, no immunity)

Total population is constant:

N=S+I

## *** Model equations*** ###


ds/dt = − beta * SI /N + gamma *I

dI/dt = beta * SI /N - gamma * I.

where , 

beta = transmission rate
gamma = recovery rate

```{r}
library(deSolve)
```

## *** Equations *** ###

```{r, equations}
sis_model <- function(time, state, parameters) {
  with(as.list(c(state, parameters)), {
    
    N <- S + I
    
    # Force of infection
    lambda <- beta * S * I / N
    
    dS <- -lambda + gamma * I
    dI <-  lambda - gamma * I
    
    list(c(dS, dI))
  })
}
```

### *** Parameters *** ####

```{r, parameters}
parameters <- c(
  beta = 0.8,    # transmission rate
  gamma = 0.2    # recovery rate
)
```

### Initial conditions ###
```{r, initals}
state <- c(
  S = 9900,    # susceptable
  I = 100    # Infected
)
```

### ** Time and simulations*** ####

```{r, time and simulations}

times <- seq(0, 100, by = 0.1)

out <- ode(
  y = state,
  times = times, 
  func = sis_model,
  parms = parameters,
)

out <- as.data.frame(out)

```

## ** Plot ** ##

```{r, ploting 1}
plot(out$time, out$S, type = "l",
     col = "blue",
     xlab = "Time",
     ylab = "Population",
     ylim = c(0, max(out$S)))

lines(out$time, out$I, col = "red")

legend("right",
       legend = c("Susceptible", "Infected"),
       col = c("blue", "red"),
       lty = 1)
```
